#!/bin/bash

# Run once the first time
python /usr/src/app/src/python/start.py

# Start resin-wifi-connect
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

sleep 1 # Delay needed to avoid DBUS introspection errors

# Run once connection_status
python /usr/src/app/src/python/connection_status.py

sudo node /usr/src/app/src/app.js --clear=false

# At this point the WiFi connection has been configured and the device has
# internet - unless the configured WiFi connection is no longer available.

# Run once connection_status
python /usr/src/app/src/python/connection_status.py

sudo node /usr/src/app/src/app2.js &

# Start the main application 
python /usr/src/app/src/python/main.py

