// Generated by CoffeeScript 1.9.3
(function() {
  var app, bodyParser, express;

  express = require('express');

  bodyParser = require('body-parser');

  app = express();

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(express["static"](__dirname + '/public'));

  app.use(function(req, res) {
    return res.redirect('/');
  });

  app.listen(80);

  retry = true;

  clear = true;

  manager = null;

}).call(this);
