// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    ssid: process.env.PORTAL_SSID || 'Raspberry Pi Hotspot',
    passphrase: process.env.PORTAL_PASSPHRASE,
    iface: process.env.PORTAL_INTERFACE || 'wlan0',
    gateway: process.env.PORTAL_GATEWAY || '192.168.23.1',
    dhcpRange: process.env.PORTAL_DHCP_RANGE || '192.168.23.2,192.168.23.254',
    connmanConfig: process.env.PORTAL_CONNMAN_CONFIG || '/var/lib/connman/network.config',
    persistentConfig: process.env.PORTAL_PERSISTENT_CONFIG || '/home/pi/network.config'
  };

}).call(this);
